[interface]
listen_port = 51820
private_key = "base64..."
address6    = "fd00:dead:beef::1/64"
address4    = "10.10.0.1/24"
dns         = ["fd00:dead:beef::1", "10.10.0.1"]

[[peers]]
public_key            = "peer1pub"
allowed_ips           = ["fd00:dead:beef::100/128", "10.10.0.100/32"]
persistent_keepalive  = 25
endpoint              = "203.0.113.10:51820"
[peers.wg_policy]
role = "general"

[[peers]]
public_key           = "peer2pub"
allowed_ips          = ["fd00:dead:beef::101/128", "10.10.0.101/32"]

[peers.wg_policy]
role = "admin"
