[package]
name = "owl-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true}
owl-application = { path = "../owl-application" }
