[package]
name = "owl-core-bin"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
owl-api = { path = "../owl-api" }
owl-application = { path = "../owl-application" }