[package]
name = "owl-application"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
owl-domain = { path = "../owl-domain" }
owl-infra  = { path = "../owl-infra" }
